### ISSUE TITLE
 I have a problem with Nox Player (Apple Login)

### ISSUE THREAD

**Issue by kramer0426** [jameschun7/universal-sdk-unity-demo#2]
Hi~

It works fine at vertically long resolutions. However, there is a problem with the horizontally long resolution.

The problem is that after processing the Apple login, the game fails to return and the Apple login page is called again.

Any solution for this?

Any help would be appreciated~

**Comment by coolishbee** [comment]
Let me ask you a few questions.
1. Does the problem occur on mobile devices?
2. Does the problem occur in other app players (BlueStacks, LDplayer) besides Nox?
3. Are there cases where the horizontal and vertical resolutions are switched during runtime?

Thanks

**Comment by kramer0426** [comment]
1. On PC device
2. LDplayer and Nox Player
3. The player's resolution is horizontally tall. My game is a portrait screen resolution

It seems that there is screen rotation in the process of running the app. I will leave a link with the video attached.
Thanks~

https://drive.google.com/file/d/13Kz_BZCB77uGKnjx3rg_4QnchdbQkqMW/view?usp=sharing

**Comment by coolishbee** [comment]
한국분이시네요

일단 원인은 앱플레이어에서 CustomTabs라는 크롬앱 기반의 웹뷰 대체재가 지원되지 않아서에요

그래서 현재 Fallback 처리로 웹뷰로 실행되는건데 웹뷰는 특성상 orientation 이 바뀌게 되면 액티비티내의 데이터가 초기화되는 성질을 갖고 있기 때문에 응답을 받을 수가 없어요

문제를 해결할 수 있는 방법은 두가지인데
1. apk 빌드시 orientation 를 auto 가 아닌 portrait 로 고정하거나
2. androidmanifest.xml 내에서 `configChanges=”orientation|screenSize` 를 추가하여 액티비티의 재생성을 방지해야 합니다

현재로서는 1번 방법을 추천드립니다~! 만약 게임 흐름상 가로모드로 변환을 줘야 한다면 2번을 선택해야 하구요

그리고 이슈트레킹은 [sdk 공식 레포지토리 이슈 트레커](https://github.com/jameschun7/universal-sdk-unity/issues)를 이용 부탁드릴게요

감사합니다

**Comment by kramer0426** [comment]
안녕하세요~
2번으로 해결해야 겠네요.
답변 감사합니다.

-----Original Message-----
